//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roller
    {
        public int rol_id { get; set; }
        public string rol_adi { get; set; }
    }
}
