//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Ticaret.Models
{
    using System;
    using System.Collections.Generic;
	public partial class Saticilar
	{
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Saticilar()
        {
            this.Urunler = new HashSet<Urunler>();
        }

	
		public int satici_id { get; set; }
		[Display(Name = "Þirket Adý")]
		[Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz")]
		public string sirket_adi { get; set; }
		[Display(Name = "Satýcý Ad Soyad")]
		[Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz")]
		public string satici_ad_soyad { get; set; }
		[Display(Name = "Telefon")]
		[Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz")]
		public string telefon { get; set; }
		[Display(Name = "E-Mail")]
		[Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz")]
		public string email { get; set; }
		[Display(Name = "Adres")]
		[Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz")]
		public string adres { get; set; }
		[Display(Name = "Ülke")]
		[Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz")]
		public string ulke { get; set; }
		[Display(Name = "Þehir")]
		[Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz")]
		public string sehir { get; set; }
		[Display(Name = "Ýlçe")]
		[Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz")]
		public string ilce { get; set; }
        public Nullable<int> musteri_id { get; set; }
		public string LoginErrorMessage { get; set; }
		public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}
