//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int sepet_id { get; set; }
        public int musteri_id { get; set; }
        public int urun_id { get; set; }
        public int adet { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
